project:
  seed: 42

banks:
  names: ["bank_s", "bank_m", "bank_l"]
  amlsim_config_dir: "configs/amlsim"

paths:
  data_raw: "data/raw"
  data_processed: "data/processed"
  outputs_root: "outputs"
  out_fl_clients: "outputs/fl_clients"
  out_fl_server: "outputs/fl_server"

preprocess:
  keep_cols:
    - acct_id
    - initial_deposit
    - state

baseline:
  top_k: 100
  alpha_grid: [1e-3, 1e-4, 1e-5]
  max_rounds: 10
  patience: 3
  out_dir: "outputs/local_baseline"

fl:
  fk_key: true
  secure_agg_key: "simulated_secure_agg_key"
  num_rounds: 10
  local_epochs: 1
  patience: 3
  alpha: 1e-4
  alpha_grid: [1e-3, 1e-4, 1e-5]

schema:
  version: "v1"
  cat_cols: ['state']
  num_cols: ['initial_deposit', 'out_cnt', 'in_cnt', 'net_flow']
  #num_cols: ['initial_deposit', 'out_cnt', 'out_sum', 'out_nuniq_bene', 'in_cnt', 'in_sum', 'in_nuniq_orig', 'net_flow', 'out_max_daily_cnt', 'out_max_daily_sum', 'in_max_daily_cnt', 'in_max_daily_sum']
